### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sergeevabc** [doodlesbykumbi/github-secrets-writer#1]
Dear @doodlesbykumbi, could you be so kind to add a real life example.
Without one the value of this app remains vague, at least to profane users.

**Comment by doodlesbykumbi** [comment]
Thanks for your comment @sergeevabc. I've provided more links to Github docs and an example of writing and consuming the secrets in the README https://github.com/doodlesbykumbi/github-secrets-writer#write-secrets. Let me know what you think of that.

**Comment by sergeevabc** [comment]
Apparently, this app is addressed to developers who are familiar with the term “github secrets”. 
I was definitely misled by it, it seemed to be somehow related to creating secret gists (pastes).
